# Generated by Django 4.1.3 on 2022-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_category_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
