# Generated by Django 4.1.3 on 2022-11-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_instagram_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram_category',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
