# Generated by Django 4.1.3 on 2022-11-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_instagram_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.URLField(max_length=1000),
        ),
    ]
