# Generated by Django 4.1.3 on 2022-11-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instagram_category',
            field=models.CharField(default='', max_length=1300, null=True),
        ),
    ]
